Name: Test-Github-Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Run a One-line script
       run: echo Hello, world!

     - name: Run another line script
       run: |
        echo this is one line,
        echo test, and deploy your project.
