name: testing workflow

on:
  push:
    branches: [ "main" ]
    paths: "k8s/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: this is simple echo task
        run: echo Hello world
